'use client';

import { useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import PageShell from '@/components/page-shell';
import StatusBadge from '@/components/status-badge';
import Loading from '@/components/loading';
import EmptyState from '@/components/empty-state';
import ErrorState from '@/components/error-state';
import Card from '@/components/card';
import { ClipboardCheck, Filter } from 'lucide-react';

export default function ReviewsPage() {
  const [reviews, setReviews] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState('');

  const load = useCallback(() => {
    setLoading(true);
    setError(null);
    const params: Record<string, string> = {};
    if (statusFilter) params.status = statusFilter;
    api.listReviews(Object.keys(params).length ? params : undefined)
      .then((data) => setReviews(data.review_tasks || []))
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [statusFilter]);

  useEffect(() => { load(); }, [load]);

  const openCount = reviews.filter(r => r.status?.toLowerCase() === 'open').length;

  return (
    <PageShell 
      title="Review Tasks" 
      subtitle="Pending and historical governance reviews generated by the compliance engine."
      breadcrumbs={[{ label: 'Reviews' }]}
    >
      <div className="space-y-6">
        {/* KPI & Filter Row */}
        <div className="flex flex-col lg:flex-row gap-6">
          <div className="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Card title="Open Tasks" variant="stat">
              <span className="text-3xl font-bold text-amber-500">{openCount}</span>
            </Card>
            <Card title="Completed" variant="stat">
              <span className="text-3xl font-bold text-zinc-300">{reviews.length - openCount}</span>
            </Card>
          </div>

          <Card className="flex items-center gap-4 bg-zinc-950 p-4">
            <div className="flex items-center gap-2 text-xs font-bold text-zinc-500 uppercase tracking-widest border-r border-border pr-4 mr-2">
              <Filter className="h-3.5 w-3.5 text-zinc-600" />
              Filter
            </div>
            <div className="flex gap-2">
              {[
                { label: 'All Tasks', value: '' },
                { label: 'Pending', value: 'open' },
                { label: 'Resolved', value: 'closed' }
              ].map((filter) => (
                <button
                  key={filter.value}
                  onClick={() => setStatusFilter(filter.value)}
                  className={`
                    px-3 py-1.5 rounded-md text-[10px] font-bold uppercase tracking-wider transition-all
                    ${statusFilter === filter.value
                      ? 'bg-zinc-100 text-black shadow-sm'
                      : 'text-zinc-500 hover:text-zinc-300 hover:bg-zinc-900'}
                  `}
                >
                  {filter.label}
                </button>
              ))}
            </div>
          </Card>
        </div>

        {loading ? (
          <Loading />
        ) : error ? (
          <ErrorState message={error} onRetry={load} />
        ) : reviews.length === 0 ? (
          <EmptyState 
            title="No review tasks generated" 
            message="Your AI features are currently operating within established governance thresholds."
            icon={ClipboardCheck}
          />
        ) : (
          <Card className="!p-0 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr>
                    <th>Review Type</th>
                    <th>Target Feature</th>
                    <th>Trigger Reason</th>
                    <th>Severity</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {reviews.map((r: any) => (
                    <tr key={r.review_task_id}>
                      <td>
                        <span className="text-[10px] font-bold text-zinc-300 uppercase tracking-widest bg-zinc-900 px-2 py-1 rounded">
                          {r.review_type}
                        </span>
                      </td>
                      <td className="text-[10px] font-mono text-zinc-400">{r.feature_id || '—'}</td>
                      <td className="text-xs text-zinc-500 max-w-xs">{r.trigger_reason}</td>
                      <td><StatusBadge value={r.severity} /></td>
                      <td><StatusBadge value={r.status} /></td>
                      <td>
                        <button className="text-[10px] font-bold text-indigo-400 hover:text-indigo-300 uppercase tracking-widest">
                          View Details
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        )}
      </div>
    </PageShell>
  );
}
